//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMKTech.Communication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GeneralSetting
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Host { get; set; }
        public Nullable<bool> SSL { get; set; }
        public Nullable<bool> UseDefaultCredentials { get; set; }
        public Nullable<int> Port { get; set; }
        public string Title { get; set; }
        public string Meta { get; set; }
        public string Keyword { get; set; }
        public string Discription { get; set; }
        public string TagLine { get; set; }
    }
}
