//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMKTech.Communication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Category
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> OrderNo { get; set; }
    }
}
