//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMKTech.Communication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdminLogin
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Fk_Role { get; set; }
        public string Email { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
    }
}
