//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMKTech.Communication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Role
    {
        public tbl_Role()
        {
            this.tbl_AdminLogin = new HashSet<tbl_AdminLogin>();
        }
    
        public int Id { get; set; }
        public string Role { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<tbl_AdminLogin> tbl_AdminLogin { get; set; }
    }
}
